// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbk6YWNYE9zjscoyIEAj-QY2bQPZOf_Bs',
    appId: '1:673244682543:web:1d6f2d35b1610d48bb29da',
    messagingSenderId: '673244682543',
    projectId: 'eat-out-round-about',
    authDomain: 'eat-out-round-about.firebaseapp.com',
    databaseURL: 'https://eat-out-round-about.firebaseio.com',
    storageBucket: 'eat-out-round-about.appspot.com',
    measurementId: 'G-VVPP14CBXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJQ4ODdxkQyKhFs8MQdBaIGVpnrWfhtA',
    appId: '1:673244682543:android:a17dcf57c984df99bb29da',
    messagingSenderId: '673244682543',
    projectId: 'eat-out-round-about',
    databaseURL: 'https://eat-out-round-about.firebaseio.com',
    storageBucket: 'eat-out-round-about.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIOmUHBKzB0kMuU2u9SaYN_zh9ZASVhVw',
    appId: '1:673244682543:ios:4e7265af174cfed3bb29da',
    messagingSenderId: '673244682543',
    projectId: 'eat-out-round-about',
    databaseURL: 'https://eat-out-round-about.firebaseio.com',
    storageBucket: 'eat-out-round-about.appspot.com',
    androidClientId: '673244682543-4jdl3iaeoumlg0370lt3m4474qvbenn5.apps.googleusercontent.com',
    iosClientId: '673244682543-gapkmjh7k4bdltg5m81kkjttlcm155c1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatoutroundabout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIOmUHBKzB0kMuU2u9SaYN_zh9ZASVhVw',
    appId: '1:673244682543:ios:d40f9b8edab7b097bb29da',
    messagingSenderId: '673244682543',
    projectId: 'eat-out-round-about',
    databaseURL: 'https://eat-out-round-about.firebaseio.com',
    storageBucket: 'eat-out-round-about.appspot.com',
    androidClientId: '673244682543-4jdl3iaeoumlg0370lt3m4474qvbenn5.apps.googleusercontent.com',
    iosClientId: '673244682543-uatb95tsva4cqrijq58hh2knjkqoktpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatoutroundabout.RunnerTests',
  );
}
